server:
  port: 8090
spring:
  application:
    name: anbu-worker
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

filas:
  proprietario: chakranet.jobs.proprietarios

management:
  tracing:
    sampling:
      probability: 1.0
tracing:
  url: ${TRACING_URL:http://localhost:4317}